//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transferencias.Resources.Values {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Transferencias.Resources.Values.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se cargó la URL de la API..
        /// </summary>
        internal static string AlertErrorApiUrlConfig {
            get {
                return ResourceManager.GetString("AlertErrorApiUrlConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pueden dejar campos en blanco.
        /// </summary>
        internal static string AlertErrorBlankField {
            get {
                return ResourceManager.GetString("AlertErrorBlankField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se configuraron los depósitos correctamente.
        /// </summary>
        internal static string AlertErrorDepoConfig {
            get {
                return ResourceManager.GetString("AlertErrorDepoConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error obteniendo los depositos guardados..
        /// </summary>
        internal static string AlertErrorDepoGet {
            get {
                return ResourceManager.GetString("AlertErrorDepoGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al cargar los depósitos..
        /// </summary>
        internal static string AlertErrorDepoLoad {
            get {
                return ResourceManager.GetString("AlertErrorDepoLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se cargaron las configuraciones iniciales..
        /// </summary>
        internal static string AlertErrorInitialSettings {
            get {
                return ResourceManager.GetString("AlertErrorInitialSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiqueta no encontrada.
        /// </summary>
        internal static string AlertErrorLabelNotFoundMessage {
            get {
                return ResourceManager.GetString("AlertErrorLabelNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo cargar el usuario logueado.
        /// </summary>
        internal static string AlertErrorLoggedUserNullMessage {
            get {
                return ResourceManager.GetString("AlertErrorLoggedUserNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe ingresar una constreña.
        /// </summary>
        internal static string AlertErrorLoginBlankPassword {
            get {
                return ResourceManager.GetString("AlertErrorLoginBlankPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe ingresar un usuario.
        /// </summary>
        internal static string AlertErrorLoginBlankUser {
            get {
                return ResourceManager.GetString("AlertErrorLoginBlankUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña incorrecta.
        /// </summary>
        internal static string AlertErrorLoginInvalidPassword {
            get {
                return ResourceManager.GetString("AlertErrorLoginInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no tiene asignado correctamente el sector.\nContactar a sistemas.
        /// </summary>
        internal static string AlertErrorLoginSector {
            get {
                return ResourceManager.GetString("AlertErrorLoginSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El response fue nulo.
        /// </summary>
        internal static string AlertErrorNullResponse {
            get {
                return ResourceManager.GetString("AlertErrorNullResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error guardando las configuraciones, si el error persiste, contactar a sistemas..
        /// </summary>
        internal static string AlertErrorSavingSettings {
            get {
                return ResourceManager.GetString("AlertErrorSavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string AlertErrorTitle {
            get {
                return ResourceManager.GetString("AlertErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        internal static string AlertInfoTitle {
            get {
                return ResourceManager.GetString("AlertInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string AlertOkButton {
            get {
                return ResourceManager.GetString("AlertOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese contraseña:.
        /// </summary>
        internal static string AlertRestrictedAccessPrompt {
            get {
                return ResourceManager.GetString("AlertRestrictedAccessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso restringido.
        /// </summary>
        internal static string AlertRestrictedAccessTitle {
            get {
                return ResourceManager.GetString("AlertRestrictedAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuraciones guardadas correctamente.
        /// </summary>
        internal static string AlertSuccessConfigSavedMessage {
            get {
                return ResourceManager.GetString("AlertSuccessConfigSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de sesión correcto\nUsuario: {0}.\nNombre: {1}.
        /// </summary>
        internal static string AlertSuccessLoginMessage {
            get {
                return ResourceManager.GetString("AlertSuccessLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacion realizada correctamente.
        /// </summary>
        internal static string AlertSuccessTitle {
            get {
                return ResourceManager.GetString("AlertSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se cargó correctamente la solicitud de transferencia de insumos.
        /// </summary>
        internal static string AlertSuccessTransferenceMessage {
            get {
                return ResourceManager.GetString("AlertSuccessTransferenceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apiUrl.
        /// </summary>
        internal static string ApiUrlKey {
            get {
                return ResourceManager.GetString("ApiUrlKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9278.
        /// </summary>
        internal static string ConfigurationViewPassword {
            get {
                return ResourceManager.GetString("ConfigurationViewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to destinationDepositId.
        /// </summary>
        internal static string DestinationDepositIdKey {
            get {
                return ResourceManager.GetString("DestinationDepositIdKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loggedUser.
        /// </summary>
        internal static string LoggedUserIdKey {
            get {
                return ResourceManager.GetString("LoggedUserIdKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuracion no cargada.
        /// </summary>
        internal static string NotLoadedSetting {
            get {
                return ResourceManager.GetString("NotLoadedSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to originDepositId.
        /// </summary>
        internal static string OriginDepositIdKey {
            get {
                return ResourceManager.GetString("OriginDepositIdKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALM25M.
        /// </summary>
        internal static string SectorCodAlm25M {
            get {
                return ResourceManager.GetString("SectorCodAlm25M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRD25M.
        /// </summary>
        internal static string SectorCodPrd25M {
            get {
                return ResourceManager.GetString("SectorCodPrd25M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string TestField {
            get {
                return ResourceManager.GetString("TestField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 76c697a6-3dae-11d5-b059-004854841c8a.
        /// </summary>
        internal static string UMUnId {
            get {
                return ResourceManager.GetString("UMUnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ////Almacen.
        /// </summary>
        internal static string ViewAdrAlm25M {
            get {
                return ResourceManager.GetString("ViewAdrAlm25M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ////Produccion.
        /// </summary>
        internal static string ViewAdrPrd25M {
            get {
                return ResourceManager.GetString("ViewAdrPrd25M", resourceCulture);
            }
        }
    }
}
