//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transferencias.Resources.Values {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Endpoints {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Endpoints() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Transferencias.Resources.Values.Endpoints", typeof(Endpoints).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/appversion.
        /// </summary>
        internal static string GetAppVersion {
            get {
                return ResourceManager.GetString("GetAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Deposito.
        /// </summary>
        internal static string GetDeposito {
            get {
                return ResourceManager.GetString("GetDeposito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Deposito/{0}.
        /// </summary>
        internal static string GetDepositoId {
            get {
                return ResourceManager.GetString("GetDepositoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/EscoSector/{0}.
        /// </summary>
        internal static string GetEscoSectorId {
            get {
                return ResourceManager.GetString("GetEscoSectorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/EscoTxEstado.
        /// </summary>
        internal static string GetEscoTxEstado {
            get {
                return ResourceManager.GetString("GetEscoTxEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/EscoTxEstado/{0}.
        /// </summary>
        internal static string GetEscoTxEstadoId {
            get {
                return ResourceManager.GetString("GetEscoTxEstadoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/EscoTxEtiqueta/codigo/{0}.
        /// </summary>
        internal static string GetEscoTxEtiquetaCodigo {
            get {
                return ResourceManager.GetString("GetEscoTxEtiquetaCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/EscoTxSolicitudTransferencia.
        /// </summary>
        internal static string GetEscoTxSolicitudTransferencia {
            get {
                return ResourceManager.GetString("GetEscoTxSolicitudTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/EscoTxSolicitudTransferencia/estado/{0}.
        /// </summary>
        internal static string GetEscoTxSolicitudTransferenciaEstado {
            get {
                return ResourceManager.GetString("GetEscoTxSolicitudTransferenciaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/EscoTxSolicitudTransferencia/{0}.
        /// </summary>
        internal static string GetEscoTxSolicitudTransferenciaId {
            get {
                return ResourceManager.GetString("GetEscoTxSolicitudTransferenciaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/EscoTxTransferencia.
        /// </summary>
        internal static string GetEscoTxTransferencia {
            get {
                return ResourceManager.GetString("GetEscoTxTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/EscoTxTransferencia/estado/{0}.
        /// </summary>
        internal static string GetEscoTxTransferenciaEstado {
            get {
                return ResourceManager.GetString("GetEscoTxTransferenciaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/EscoTxTransferencia/{0}.
        /// </summary>
        internal static string GetEscoTxTransferenciaId {
            get {
                return ResourceManager.GetString("GetEscoTxTransferenciaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/EscoUsuarioApp/codigo/{0}.
        /// </summary>
        internal static string GetEscoUsuarioAppCodigo {
            get {
                return ResourceManager.GetString("GetEscoUsuarioAppCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/EscoUsuarioApp/{0}.
        /// </summary>
        internal static string GetEscoUsuarioAppId {
            get {
                return ResourceManager.GetString("GetEscoUsuarioAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Producto/{0}.
        /// </summary>
        internal static string GetProductoId {
            get {
                return ResourceManager.GetString("GetProductoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/EscoTxSolicitudTransferencia.
        /// </summary>
        internal static string PostEscoTxSolicitudTransferencia {
            get {
                return ResourceManager.GetString("PostEscoTxSolicitudTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/EscoTxTransferencia.
        /// </summary>
        internal static string PostEscoTxTransferencia {
            get {
                return ResourceManager.GetString("PostEscoTxTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/EscoUsuarioApp/login.
        /// </summary>
        internal static string PostEscoUsuarioAppLogin {
            get {
                return ResourceManager.GetString("PostEscoUsuarioAppLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/ItemInventario.
        /// </summary>
        internal static string PostItemInventario {
            get {
                return ResourceManager.GetString("PostItemInventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/EscoTxSolicitudTransferencia/{0}/estado.
        /// </summary>
        internal static string PutEscoTxSolicitudTransferenciaId {
            get {
                return ResourceManager.GetString("PutEscoTxSolicitudTransferenciaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/EscoTxTransferencia/{0}/estado.
        /// </summary>
        internal static string PutEscoTxTransferenciaId {
            get {
                return ResourceManager.GetString("PutEscoTxTransferenciaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/EscoTxItemSolicitudTransferencia/{0}.
        /// </summary>
        internal static string PutItemSolicitudTransferenciaId {
            get {
                return ResourceManager.GetString("PutItemSolicitudTransferenciaId", resourceCulture);
            }
        }
    }
}
