name: Build Android APK and Release

on:
  push:
    branches:
      - ci-cd/setup  # Se dispara cuando creas un tag como v1.0.0
  workflow_dispatch:

jobs:
  build-android:
    runs-on: windows-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Instalar .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # 3️⃣ Instalar workloads de MAUI
      - name: Install MAUI workload
        run: dotnet workload install maui

      # 4️⃣ Publicar APK firmado
      - name: Publish Android APK
        run: |
          dotnet publish MyApp/MyApp.csproj \
            -f net8.0-android \
            -c Release \
            -o ./output \
            /p:AndroidPackageFormat=apk \
            /p:AndroidKeyStore=true \
            /p:AndroidSigningKeyStore=keystore/my-release-key.keystore \
            /p:AndroidSigningKeyAlias=my-key-alias \
            /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" \
            /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD }}"

      # 5️⃣ Crear release en GitHub
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 6️⃣ Subir APK al release
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/**/*.apk
          asset_name: MyApp.apk
          asset_content_type: application/vnd.android.package-archive
