name: Build Android APK and Release

on:
  push:
    branches:
      - ci-cd/setup  # Se dispara al crear un tag como v1.0.0
  workflow_dispatch:

jobs:
  build-android:
    runs-on: windows-latest

    steps:
      # 1️⃣ Clonar repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Instalar .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # 3️⃣ Instalar MAUI workload
      - name: Install MAUI workload
        run: dotnet workload install maui
        shell: pwsh

      # 4️⃣ Restaurar keystore desde Base64 usando ruta absoluta
      - name: Restore keystore
        run: |
          $keystorePath = Join-Path $PWD "my-release-key.keystore"
          [System.IO.File]::WriteAllBytes($keystorePath, [Convert]::FromBase64String("${{ secrets.ORG_ANDROID_KEYSTORE_BASE64 }}"))
          Write-Host "Keystore path: $keystorePath"
        shell: pwsh

      # 5️⃣ Publicar APK firmado usando ruta absoluta del keystore
      - name: Publish Android APK
        run: |
          $keystorePath = Join-Path $PWD "my-release-key.keystore"
          dotnet publish "Transferencias/Transferencias.csproj" -f net8.0-android -c Release -o "$PWD\output" /p:AndroidPackageFormat=apk /p:AndroidKeyStore=true /p:AndroidSigningKeyStore=$keystorePath /p:AndroidSigningKeyAlias="${{ secrets.ORG_ANDROID_KEY_ALIAS }}" /p:AndroidSigningKeyPass="${{ secrets.ORG_ANDROID_KEY_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.ORG_ANDROID_KEYSTORE_PASSWORD }}"
        shell: pwsh

      # 6️⃣ Crear release en GitHub
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 7️⃣ Subir APK al release
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "$PWD/output/*.apk"
          asset_name: Transferencias.apk
          asset_content_type: application/vnd.android.package-archive
